# Generated by Django 4.2.16 on 2026-08-07 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tgbot', '0012_auto_20220115_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('position', 'name'), 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Buyurtma mahsuloti', 'verbose_name_plural': 'Buyurtma mahsulotlari'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-created_at',), 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('position', 'title'), 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('position', 'name'), 'verbose_name': 'Subkategoriya', 'verbose_name_plural': 'Subkategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'ordering': ('-created_at',), 'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='useraddresses',
            options={'verbose_name': 'Manzil', 'verbose_name_plural': 'Manzillar'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(blank=True, verbose_name='Yetkazish manzili'),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='orders',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Kuryer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Kuryer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqt'),
        ),
        migrations.AddField(
            model_name='orders',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_orders', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan operator'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CLICK', 'Click'), ('TRANSFER', "O'tkazma")], default='CASH', max_length=16, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('CONFIRMED', 'Tasdiqlangan'), ('PACKING', "Yig'ilmoqda"), ('ON_WAY', "Yo'lda"), ('DELIVERED', 'Yetkazildi'), ('CANCELLED', 'Bekor qilindi')], db_index=True, default='NEW', max_length=16, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AZIZON', 'Azizon'), ('AFSONA', 'Afsona')], default='AZIZON', max_length=16, verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Tarkibi'),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.CharField(blank=True, max_length=40, verbose_name='Diametri'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.TextField(blank=True, verbose_name="Ta'm yo'nalishi"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Yangi mahsulot'),
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(blank=True, help_text='masalan: yarim dudlangan kolbasa', max_length=120, verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.TextField(blank=True, verbose_name='Saqlash sharoiti'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=40, verbose_name="Og'irligi"),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloklangan'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tg_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Botdagi nomi'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='tgbot.orders', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product', to='tgbot.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='single_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Dona narxi'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langan"),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Buyurtma raqami'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tg_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tgbot.tguser', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Sotuvda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='tgbot.subcategory', verbose_name='Subkategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='tgbot.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='tg_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Botdagi nomi'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='address',
            field=models.TextField(max_length=150, verbose_name='Yetkazish manzili'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.tguser', verbose_name='Mijoz'),
        ),
    ]
