# Generated by Django 4.2.16 on 2026-08-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_alter_category_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Chegirma bo'lmasa 0 qoldiring", max_digits=12, verbose_name="Eski narxi (so'm)"),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ombordagi miqdor'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('DONA', 'dona'), ('KG', 'kg')], default='DONA', max_length=8, verbose_name="O'lchov birligi"),
        ),
    ]
