# Generated by Django 4.2.16 on 2026-08-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_product_old_price_product_stock_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Telegramsiz mijoz uchun', max_length=120, verbose_name='Mijoz ismi'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Yetkazish narxi'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_type',
            field=models.CharField(choices=[('DELIVERY', 'Yetkazib berish'), ('PICKUP', 'Olib ketish')], default='DELIVERY', max_length=16, verbose_name='Yetkazish turi'),
        ),
        migrations.AddField(
            model_name='orders',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="Mijoz so'ragan yetkazish vaqti", null=True, verbose_name='Rejalashtirilgan vaqt'),
        ),
        migrations.AddField(
            model_name='orders',
            name='source',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram bot'), ('SHOP', "Do'kondan"), ('PHONE', 'Telefon orqali')], db_index=True, default='SHOP', max_length=16, verbose_name='Sotuv kanali'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Ishlab chiqarilgan davlat'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='', help_text='masalan: 200x90x75 sm', max_length=80, verbose_name="O'lchami"),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='', help_text='masalan: MDF, teri, metall', max_length=120, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Model raqami'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, default='', help_text='masalan: 1800 Vt', max_length=40, verbose_name='Quvvati'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Kafolat (oy)'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tg_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tgbot.tguser', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Brend'),
        ),
    ]
